databases:
  - name: udemy_rest_api_database
    plan: free
    databaseName: api_db
    user: api_db

services:
  - type: web
    name: udemy_rest_api_webservice
    plan: free
    env: python
    rootDir: drf-jwt
    buildCommand: ./build.sh
    branch: main
    repo: https://github.com/sinsky/nextjs-django
    startCommand: "gunicorn rest_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
